import './style.css';

const decks = {
  beginner: { label: '초급', subtitle: '기초를 단단하게', range: 'A1 · 기초', color: 'peach', words: [
    ['achieve', '성취하다, 이루다', 'verb', 'She achieved her goal.', '그녀는 목표를 이루었다.'], ['borrow', '빌리다', 'verb', 'Can I borrow your pen?', '펜을 빌려도 될까요?'], ['choose', '선택하다', 'verb', 'Choose the best answer.', '가장 좋은 답을 선택하세요.'], ['decide', '결정하다', 'verb', 'I decided to walk home.', '나는 걸어서 집에 가기로 결정했다.'], ['enough', '충분한', 'adjective', 'We have enough time.', '우리에게는 충분한 시간이 있다.'], ['future', '미래', 'noun', 'The future looks bright.', '미래는 밝아 보인다.'], ['happy', '행복한', 'adjective', 'This song makes me happy.', '이 노래는 나를 행복하게 한다.'], ['important', '중요한', 'adjective', 'Sleep is important for health.', '잠은 건강에 중요하다.'], ['journey', '여행', 'noun', 'The journey was fun.', '그 여행은 즐거웠다.'], ['kind', '친절한', 'adjective', 'He is kind to everyone.', '그는 모두에게 친절하다.'] ] },
  intermediate: { label: '중급', subtitle: '표현의 폭을 넓게', range: 'B1 · 실전', color: 'mint', words: [
    ['anxious', '불안해하는', 'adjective', 'She felt anxious before the test.', '그녀는 시험 전에 불안했다.'], ['benefit', '이점, 혜택', 'noun', 'Exercise has many benefits.', '운동에는 많은 이점이 있다.'], ['challenge', '도전, 과제', 'noun', 'Learning a language is a challenge.', '언어 학습은 도전 과제다.'], ['describe', '묘사하다, 설명하다', 'verb', 'Can you describe the place?', '그 장소를 설명해 줄 수 있나요?'], ['essential', '필수적인', 'adjective', 'Water is essential for life.', '물은 생명에 필수적이다.'], ['familiar', '익숙한', 'adjective', 'Her voice sounded familiar.', '그녀의 목소리는 익숙하게 들렸다.'], ['generous', '관대한', 'adjective', 'It was a generous offer.', '그것은 관대한 제안이었다.'], ['hesitate', '망설이다', 'verb', 'Do not hesitate to ask.', '주저하지 말고 물어보세요.'], ['influence', '영향을 미치다', 'verb', 'Music can influence our mood.', '음악은 기분에 영향을 줄 수 있다.'], ['maintain', '유지하다', 'verb', 'Maintain a healthy balance.', '건강한 균형을 유지하세요.'] ] },
  advanced: { label: '고급', subtitle: '정교하게 다듬기', range: 'C1 · 심화', color: 'lilac', words: [
    ['ambiguous', '애매한, 모호한', 'adjective', 'His answer was ambiguous.', '그의 답변은 모호했다.'], ['coherent', '일관성 있는, 논리적인', 'adjective', 'Write a coherent argument.', '논리적인 주장을 작성하세요.'], ['deteriorate', '악화되다', 'verb', 'The weather began to deteriorate.', '날씨가 악화되기 시작했다.'], ['elaborate', '상세히 설명하다', 'verb', 'Please elaborate on your idea.', '당신의 생각을 자세히 설명해 주세요.'], ['fundamental', '근본적인', 'adjective', 'Trust is fundamental to teamwork.', '신뢰는 팀워크의 근본이다.'], ['inevitable', '피할 수 없는', 'adjective', 'Change is inevitable.', '변화는 피할 수 없다.'], ['perspective', '관점', 'noun', 'Try to see a new perspective.', '새로운 관점을 보려고 해보세요.'], ['profound', '깊은, 심오한', 'adjective', 'The book had a profound effect.', '그 책은 깊은 영향을 주었다.'], ['reluctant', '꺼리는', 'adjective', 'He was reluctant to leave.', '그는 떠나기를 꺼렸다.'], ['versatile', '다재다능한', 'adjective', 'It is a versatile tool.', '그것은 다재다능한 도구다.'] ] }
};

const state = JSON.parse(localStorage.getItem('wordly-state') || '{}');
state.level ||= 'beginner'; state.learned ||= []; state.score ||= 0; state.streak ||= 3; state.index ??= 0; state.gameIndex ??= 0;
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const save = () => localStorage.setItem('wordly-state', JSON.stringify(state));
let cardFlipped = false, answered = false, quizWords = [];

function getDeck(){ return decks[state.level]; }
function currentWord(){ return getDeck().words[state.index % getDeck().words.length]; }
function learnedForLevel(){ return state.learned.filter(x => x.startsWith(`${state.level}:`)).length; }
function setView(view){ $$('.view').forEach(v => v.classList.toggle('active', v.id === `${view}View`)); $$('.nav-link').forEach(n => n.classList.toggle('active', n.dataset.view === view)); document.querySelector('.sidebar').classList.remove('open'); if(view === 'study') renderStudy(); if(view === 'game') startGame(); if(view === 'words') renderWords(); window.scrollTo({top: 0, behavior: 'smooth'}); }
function toast(text){ const el=$('#toast'); el.textContent=text; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'), 2200); }

function renderLevels(){ $('#levelGrid').innerHTML = Object.entries(decks).map(([key, deck], i) => `<button class="level-card ${deck.color} ${state.level === key ? 'selected' : ''}" data-level="${key}"><span class="level-icon">${['◌','✦','♢'][i]}</span><span class="level-name">${deck.label}</span><span class="level-sub">${deck.subtitle}</span><span class="level-range">${deck.range}</span><span class="select-mark">${state.level === key ? '✓' : '→'}</span></button>`).join('');
  $$('.level-card').forEach(el=>el.addEventListener('click',()=>{state.level=el.dataset.level;state.index=0;save();renderLevels();renderHomeStats();toast(`${decks[state.level].label} 난이도로 준비했어요`);}));
}
function renderHomeStats(){ const total=state.learned.length; const count=Math.min(10,total); $('#goalCount').textContent=`${count} / 10 단어`; $('#goalProgress').style.width=`${count*10}%`; $('#goalNote').textContent=count?`오늘 ${count}개의 단어를 기억했어요. 아주 좋아요!`:'첫 단어를 만나러 가볼까요?'; $('#streakNumber').textContent=state.streak; $('#sidebarStreak').textContent=`🔥 ${state.streak}일째 이어가는 중`;
  const today=new Date(); $('#todayDate').textContent=`${today.getMonth()+1}월 ${today.getDate()}일, 오늘도 한 걸음`;
  $('#weekDays').innerHTML=['월','화','수','목','금','토','일'].map((d,i)=>`<span class="${i<state.streak?'done':''}"><b>${i<state.streak?'✓':'·'}</b>${d}</span>`).join('');
}
function renderStudy(){ const d=getDeck(), w=currentWord(), done=learnedForLevel(); cardFlipped=false; $('#flashCard').classList.remove('flipped'); $('#studyLevelName').textContent=d.label; $('#currentDeck').textContent=`${d.label} · ${d.label==='초급'?'필수 100':d.label==='중급'?'표현력 100':'심화 100'}`; $('#wordText').textContent=w[0]; $('#wordType').textContent=w[2]; $('#meaningText').textContent=w[1]; $('#exampleText').textContent=w[3]; $('#exampleMeaning').textContent=w[4]; $('#sessionNumber').textContent=`${state.index % d.words.length + 1} / ${d.words.length}`; $('#deckLearned').textContent=done; $('#deckProgress').style.width=`${Math.min(100, done*10)}%`; }
function flip(){cardFlipped=!cardFlipped;$('#flashCard').classList.toggle('flipped',cardFlipped);}
function rate(rating){ const key=`${state.level}:${currentWord()[0]}`; if(!state.learned.includes(key)) state.learned.push(key); if(rating==='easy') state.score+=3; if(rating==='good') state.score+=2; state.index=(state.index+1)%getDeck().words.length; save(); renderStudy();renderHomeStats(); toast(rating==='hard'?'다음에 한 번 더 만나요.':'기억 상자에 저장했어요!'); }
function speak(){ if(!('speechSynthesis' in window)){toast('이 브라우저는 발음을 지원하지 않아요.');return;} const u=new SpeechSynthesisUtterance(currentWord()[0]);u.lang='en-US';u.rate=.78;speechSynthesis.cancel();speechSynthesis.speak(u); }

function shuffled(arr){return [...arr].sort(()=>Math.random()-.5);}
function startGame(){ const words=shuffled(getDeck().words); quizWords=words.slice(0,10); state.gameIndex=0; state.roundScore=0; answered=false; renderQuestion(); }
function renderQuestion(){ if(state.gameIndex>=quizWords.length){ $('#quizMeaning').textContent=`완료! ${state.roundScore}점을 얻었어요.`;$('#answers').innerHTML='<div class="game-complete">🎉<br><b>오늘의 점검을 마쳤어요!</b><span>새 게임을 시작해 복습해 보세요.</span></div>';$('#roundNumber').textContent='10';$('#roundProgress').style.width='100%';$('#nextQuestion').hidden=false;$('#nextQuestion').textContent='새 게임 시작 →';$('#feedback').textContent='';return; } answered=false;const word=quizWords[state.gameIndex], options=shuffled([word,...shuffled(getDeck().words.filter(w=>w[0]!==word[0])).slice(0,3)]);$('#roundNumber').textContent=String(state.gameIndex+1).padStart(2,'0');$('#roundProgress').style.width=`${state.gameIndex*10}%`;$('#quizMeaning').textContent=word[1];$('#answers').innerHTML=options.map((w,i)=>`<button class="answer" data-word="${w[0]}"><span>${String.fromCharCode(65+i)}</span>${w[0]}</button>`).join('');$('#feedback').textContent='';$('#nextQuestion').hidden=true;$$('.answer').forEach(btn=>btn.addEventListener('click',()=>answer(btn,word)));}
function answer(btn,correct){if(answered)return;answered=true;const isCorrect=btn.dataset.word===correct[0];$$('.answer').forEach(b=>{if(b.dataset.word===correct[0])b.classList.add('correct');else if(b===btn)b.classList.add('wrong');b.disabled=true;}); if(isCorrect){state.roundScore+=10;state.score+=10;$('#feedback').textContent='정답이에요! 멋져요 ✦';$('#feedback').className='feedback correct-text';} else {$('#feedback').textContent=`아쉬워요. 정답은 ${correct[0]}예요.`;$('#feedback').className='feedback wrong-text';} $('#gameScore').textContent=state.score; save();$('#nextQuestion').hidden=false; }
function nextQuestion(){if(state.gameIndex>=quizWords.length){startGame();return;}state.gameIndex++;renderQuestion();}
function renderWords(){ const order=[...Object.entries(decks)]; $('#wordList').innerHTML=order.map(([key,d])=>{const ws=state.learned.filter(x=>x.startsWith(`${key}:`)).map(x=>x.split(':')[1]);return `<section class="word-group"><div><span class="dot ${d.color}"></span><h3>${d.label}</h3><small>${ws.length}개 학습함</small></div>${ws.length?`<ul>${ws.map(word=>`<li><b>${word}</b><span>${d.words.find(w=>w[0]===word)?.[1]}</span><i>✓</i></li>`).join('')}</ul>`:'<p class="empty-words">아직 학습한 단어가 없어요.</p>'}</section>`}).join(''); }

$$('.nav-link').forEach(n=>n.addEventListener('click',()=>setView(n.dataset.view)));$$('[data-view-target]').forEach(n=>n.addEventListener('click',()=>setView(n.dataset.viewTarget)));$('.logo').addEventListener('click',e=>{e.preventDefault();setView('home')});$('#flashCard').addEventListener('click',flip);$('#flashCard').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();flip();}});$$('.rating').forEach(b=>b.addEventListener('click',()=>rate(b.dataset.rating)));$('#listenWord').addEventListener('click',e=>{e.stopPropagation();speak();});$('#soundToggle').addEventListener('click',speak);$('#nextQuestion').addEventListener('click',nextQuestion);$('#mobileMenu').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));
renderLevels();renderHomeStats();renderStudy();$('#gameScore').textContent=state.score;
